version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_NAME: my_database
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
